# Config file for automatic testing at travis-ci.org

language: python
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy

install:
  - pip install coveralls

script:
  - python setup.py develop
  - coverage run --source=pytest_datafiles.py runtests.py

after_success:
  - coveralls
